name: Flutter Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          # Cherche le pubspec.yaml et installe les dépendances là où il se trouve
          cd $(find . -name pubspec.yaml -exec dirname {} \;)
          flutter pub get

      - name: Clean and Build
        run: |
          # 1. On trouve le dossier android
          ANDROID_DIR=$(find . -name android -type d -print -quit)
          PROJECT_ROOT=$(dirname $ANDROID_DIR)
          
          cd $PROJECT_ROOT
          
          # 2. Nettoyage des scories locales
          rm -f android/local.properties
          [ -f android/gradle.properties ] && sed -i '/org.gradle.java.home/d' android/gradle.properties || true
          
          # 3. Rendre gradlew exécutable
          chmod +x android/gradlew
          
          # 4. Lancement du Build Release
          flutter config --jdk-dir $JAVA_HOME
          flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flutter-release-apk
          path: "**/build/app/outputs/flutter-apk/*.apk"

